### ISSUE TITLE
run.go error

### ISSUE THREAD

**Issue by globalme** [cdnlysis/cdnlysis#3]
Everytime I try to run the Readme example (go run run.go), I get the following error:

```
# command-line-arguments
./run.go:17: syntax error: missing channel element type
```

**Comment by meson10** [comment]
I have updated the documentation for this. Also, cdnlysis was a component in itself but now its a library. Purpose is to hand out a channel of LogRecords which you can do whatever you want to with it.

One example implementation of this is https://github.com/cdnlysis/cdnlysis_influxdb which uses this library to save records in InfluxDB.
